#!/bin/sh
# /usr/share/parental-privacy/safesearch.sh
#
# Enforces SafeSearch on Google, Bing, YouTube, DuckDuckGo, Brave, and
# Pixabay via dnsmasq CNAME/address records. Works by pointing search domains
# at the provider's own SafeSearch enforcement IPs — no DPI or SSL inspection
# required.
#
# Usage:
#   safesearch.sh enable   — write rules and restart dnsmasq
#   safesearch.sh disable  — remove rules and restart dnsmasq
#   safesearch.sh status   — print current state
#
# UCI options read:
#   parental_privacy.default.youtube_mode   moderate|strict  (default: moderate)
#   parental_privacy.default.block_search   0|1              (default: 0)
#   parental_privacy.default.undesirable    0|1              (default: 0)

DNSMASQ_CONF="/tmp/dnsmasq.kids.d/safesearch.conf"
# Persistent copy so the file survives reboots — parental-privacy.init
# copies /etc/dnsmasq.kids.d/ into /tmp/dnsmasq.kids.d/ on startup.
DNSMASQ_CONF_PERSIST="/etc/dnsmasq.kids.d/safesearch.conf"

# ── Google ───────────────────────────────────────────────────────────────────
# forcesafesearch.google.com is Google's official SafeSearch enforcement host.
# We CNAME all regional and product Google search domains to it.
# Google then enforces SafeSearch server-side on every result page.
GOOGLE_SAFE_HOST="forcesafesearch.google.com"
GOOGLE_DOMAINS="
www.google.com
www.google.co.uk
www.google.com.au
www.google.ca
www.google.de
www.google.fr
www.google.es
www.google.it
www.google.co.jp
www.google.co.in
www.google.com.br
www.google.com.mx
www.google.nl
www.google.pl
www.google.ru
www.google.se
www.google.ch
www.google.be
www.google.at
www.google.dk
www.google.fi
www.google.no
www.google.pt
www.google.ie
www.google.co.nz
www.google.co.za
www.google.com.ar
www.google.com.co
www.google.com.pe
www.google.gr
www.google.hu
www.google.cz
www.google.ro
www.google.bg
www.google.hr
www.google.sk
www.google.si
www.google.lt
www.google.lv
www.google.ee
"

# ── Bing ─────────────────────────────────────────────────────────────────────
# strict.bing.com is Microsoft's SafeSearch enforcement host.
BING_SAFE_HOST="strict.bing.com"
BING_DOMAINS="
www.bing.com
bing.com
"

# ── YouTube ──────────────────────────────────────────────────────────────────
# restrict.youtube.com    = Moderate restriction (blocks most adult content)
# restrictmd.youtube.com  = Strict restriction (supervised mode, very locked down)
# Moderate is the better default — strict blocks too much legitimate content.
# Read from UCI: parental_privacy.default.youtube_mode (moderate|strict)
YOUTUBE_MODE=$(uci -q get parental_privacy.default.youtube_mode)
YOUTUBE_MODE=${YOUTUBE_MODE:-moderate}
case "$YOUTUBE_MODE" in
    strict)   YOUTUBE_SAFE_HOST="restrictmd.youtube.com" ;;
    *)        YOUTUBE_SAFE_HOST="restrict.youtube.com"   ;;
esac
YOUTUBE_DOMAINS="
www.youtube.com
m.youtube.com
youtubei.googleapis.com
youtube.googleapis.com
www.youtube-nocookie.com
"

# ── DuckDuckGo ───────────────────────────────────────────────────────────────
DUCKDUCKGO_SAFE_HOST="safe.duckduckgo.com"
DUCKDUCKGO_DOMAINS="
duckduckgo.com
www.duckduckgo.com
"

# ── Brave Search ──────────────────────────────────────────────────────────────
# forcesafe.search.brave.com enforces SafeSearch at the server level.
# The host-record ensures the enforcement host resolves correctly; the CNAME
# redirects all Brave Search queries through it.
BRAVE_SAFE_HOST="forcesafe.search.brave.com"
BRAVE_SAFE_IP="108.138.246.75"
BRAVE_DOMAINS="
search.brave.com
"

# ── Pixabay ───────────────────────────────────────────────────────────────────
# Pixabay uses CNAME-based SafeSearch enforcement.
PIXABAY_SAFE_HOST="safesearch.pixabay.com"
PIXABAY_DOMAINS="
pixabay.com
www.pixabay.com
"

# ── Block Uncontrolled Search Engines ────────────────────────────────────────
# When enabled, search engines that have no SafeSearch enforcement mechanism
# (or whose mechanism cannot be enforced at DNS level) are blocked entirely.
# This prevents children from bypassing SafeSearch by switching to an
# obscure engine. Controlled by UCI:
#   parental_privacy.default.block_search  0|1  (default: 0)
BLOCK_SEARCH=$(uci -q get parental_privacy.default.block_search)
BLOCK_SEARCH=${BLOCK_SEARCH:-0}

# Engines that cannot enforce SafeSearch via DNS CNAME/address tricks.
# Excludes Google, Bing, DuckDuckGo, Brave, and Yahoo (which uses Bing).
UNCONTROLLED_SEARCH_ENGINES="
search.yahoo.co.jp
uk.search.yahoo.com
fr.search.yahoo.com
de.search.yahoo.com
search.aol.com
search.lycos.com
www.ask.com
www.dogpile.com
www.startpage.com
www.ecosia.org
www.qwant.com
search.yahoo.com
www.yandex.com
yandex.ru
yandex.com
www.baidu.com
baidu.com
search.seznam.cz
www.naver.com
search.naver.com
www.sogou.com
www.so.com
www.wolframalpha.com
www.metacrawler.com
www.webcrawler.com
search.yahoo.fr
"

write_conf() {
    cat > "$DNSMASQ_CONF" <<EOF
# SafeSearch enforcement — managed by parental-privacy
# Generated by safesearch.sh — do not edit manually

EOF

    # Google — CNAME all regional domains to the safe host
    echo "# Google SafeSearch" >> "$DNSMASQ_CONF"
    for domain in $GOOGLE_DOMAINS; do
        echo "cname=${domain},${GOOGLE_SAFE_HOST}" >> "$DNSMASQ_CONF"
    done
    echo "" >> "$DNSMASQ_CONF"

    # Bing
    echo "# Bing SafeSearch" >> "$DNSMASQ_CONF"
    for domain in $BING_DOMAINS; do
        echo "cname=${domain},${BING_SAFE_HOST}" >> "$DNSMASQ_CONF"
    done
    echo "" >> "$DNSMASQ_CONF"

    # YouTube — mode is moderate or strict, selected via YOUTUBE_MODE UCI option
    echo "# YouTube Restricted Mode (${YOUTUBE_MODE})" >> "$DNSMASQ_CONF"
    for domain in $YOUTUBE_DOMAINS; do
        echo "cname=${domain},${YOUTUBE_SAFE_HOST}" >> "$DNSMASQ_CONF"
    done
    echo "" >> "$DNSMASQ_CONF"

    # DuckDuckGo
    echo "# DuckDuckGo Restricted Mode" >> "$DNSMASQ_CONF"
    for domain in $DUCKDUCKGO_DOMAINS; do
        echo "cname=${domain},${DUCKDUCKGO_SAFE_HOST}" >> "$DNSMASQ_CONF"
    done
    echo "" >> "$DNSMASQ_CONF"

    # Brave Search
    echo "# Brave Search SafeSearch" >> "$DNSMASQ_CONF"
    # host-record resolves the enforcement host to its IP
    echo "host-record=${BRAVE_SAFE_HOST},${BRAVE_SAFE_IP}" >> "$DNSMASQ_CONF"
    for domain in $BRAVE_DOMAINS; do
        echo "cname=${domain},${BRAVE_SAFE_HOST}" >> "$DNSMASQ_CONF"
    done
    echo "" >> "$DNSMASQ_CONF"

    # Pixabay
    echo "# Pixabay SafeSearch" >> "$DNSMASQ_CONF"
    for domain in $PIXABAY_DOMAINS; do
        echo "cname=${domain},${PIXABAY_SAFE_HOST}" >> "$DNSMASQ_CONF"
    done
    echo "" >> "$DNSMASQ_CONF"

    # Block uncontrolled search engines (optional)
    if [ "$BLOCK_SEARCH" = "1" ]; then
        echo "# Block uncontrolled search engines" >> "$DNSMASQ_CONF"
        for domain in $UNCONTROLLED_SEARCH_ENGINES; do
            echo "address=/${domain}/" >> "$DNSMASQ_CONF"
        done
        echo "" >> "$DNSMASQ_CONF"
    fi

	# TikTok & Snapchat Domains
	# Hardcoded entries remain as an instant fallback; hagezi_tiktok (below)
	# extends coverage to the full ByteDance/TikTok infrastructure when enabled.
	TIKTOK_DOMAINS="tiktok.com tiktokv.com musical.ly byteoversea.com tiktokcdn.com"
	SNAPCHAT_DOMAINS="snapchat.com sc-static.net snapads.com"
	BLOCK_UNDESIRABLE=$(uci -q get parental_privacy.default.undesirable)
	if [ "$BLOCK_UNDESIRABLE" = "1" ]; then
		echo "# Block Undesirable Apps" >> "$DNSMASQ_CONF"
		for d in $TIKTOK_DOMAINS $SNAPCHAT_DOMAINS; do
			echo "address=/${d}/" >> "$DNSMASQ_CONF"
		done
	fi
}


# ── HaGeZi NoSafeSearch integration ──────────────────────────────────────────
# When SafeSearch is enabled we also force-enable the hagezi_nosafesearch
# blocklist in UCI so it is included in the next nightly update-blocklists.sh
# run.  We also immediately append its entries to the live conf file so the
# protection takes effect right now rather than waiting until 03:00.
#
# When SafeSearch is disabled we release the force — if the user had it manually
# enabled beforehand the enabled flag is left as-is; we only ever set it to 1,
# never force it back to 0.
#
HAGEZI_NOSAFESEARCH_URL="https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/nosafesearch.txt"
HAGEZI_NOSAFESEARCH_CACHE="/tmp/hagezi_nosafesearch.cache"
LIVE_BLOCKLIST="/etc/dnsmasq.kids.d/dns_blocklist.conf"

_nosafesearch_enable_uci() {
    # Mark the list as enabled in UCI so the nightly script includes it.
    # Also ensure the section exists with the correct metadata in case the
    # catalog sync hasn't run yet (e.g. right after a fresh install).
    local _existing
    _existing=$(uci -q get parental_privacy.blocklist_hagezi_nosafesearch.id 2>/dev/null)
    if [ -z "$_existing" ]; then
        uci -q batch <<EOI
set parental_privacy.blocklist_hagezi_nosafesearch=blocklist
set parental_privacy.blocklist_hagezi_nosafesearch.id='hagezi_nosafesearch'
set parental_privacy.blocklist_hagezi_nosafesearch.name='No SafeSearch'
set parental_privacy.blocklist_hagezi_nosafesearch.url='${HAGEZI_NOSAFESEARCH_URL}'
set parental_privacy.blocklist_hagezi_nosafesearch.size_hint='small'
set parental_privacy.blocklist_hagezi_nosafesearch.description='Blocks search engines that do not support or enforce a Strict SafeSearch mode.'
set parental_privacy.blocklist_hagezi_nosafesearch.enabled='1'
EOI
    else
        uci -q set parental_privacy.blocklist_hagezi_nosafesearch.enabled='1'
    fi
    uci -q commit parental_privacy
}

_nosafesearch_append_live() {
    # Download (or use cache) and append the list's entries directly to the
    # live blocklist conf so they take effect immediately on dnsmasq restart.
    # If the live blocklist file doesn't exist yet we skip — it will be created
    # by update-blocklists.sh at 03:00 and the UCI enabled flag ensures the
    # list is included at that point.
    [ -f "$LIVE_BLOCKLIST" ] || return

    # Use cache if present (cleared on reboot, re-fetched once per boot)
    if [ ! -s "$HAGEZI_NOSAFESEARCH_CACHE" ]; then
        logger -t parental-privacy "SafeSearch: fetching hagezi_nosafesearch list..."
        if wget -q --timeout=20 -O "${HAGEZI_NOSAFESEARCH_CACHE}.tmp" "$HAGEZI_NOSAFESEARCH_URL" 2>/dev/null; then
            if grep -qE '^(address|server)=/' "${HAGEZI_NOSAFESEARCH_CACHE}.tmp" 2>/dev/null; then
                mv "${HAGEZI_NOSAFESEARCH_CACHE}.tmp" "$HAGEZI_NOSAFESEARCH_CACHE"
                logger -t parental-privacy "SafeSearch: hagezi_nosafesearch fetched ($(wc -l < "$HAGEZI_NOSAFESEARCH_CACHE") lines)."
            else
                rm -f "${HAGEZI_NOSAFESEARCH_CACHE}.tmp"
                logger -t parental-privacy "SafeSearch: hagezi_nosafesearch download invalid — skipping live append."
                return
            fi
        else
            rm -f "${HAGEZI_NOSAFESEARCH_CACHE}.tmp"
            logger -t parental-privacy "SafeSearch: hagezi_nosafesearch download failed — will be included at next 03:00 update."
            return
        fi
    fi

    # Only append if entries aren't already present (idempotent)
    if grep -q "# hagezi_nosafesearch" "$LIVE_BLOCKLIST" 2>/dev/null; then
        logger -t parental-privacy "SafeSearch: hagezi_nosafesearch already present in live blocklist."
        return
    fi

    {
        echo ""
        echo "# hagezi_nosafesearch — appended by safesearch.sh"
        grep -E '^(address|server)=/' "$HAGEZI_NOSAFESEARCH_CACHE"
    } >> "$LIVE_BLOCKLIST"

    logger -t parental-privacy "SafeSearch: hagezi_nosafesearch appended to live blocklist."
}

_nosafesearch_remove_live() {
    # Remove the entries appended by safesearch.sh from the live blocklist.
    # Uses sed to strip from the marker comment to the next blank line or EOF.
    [ -f "$LIVE_BLOCKLIST" ] || return
    if grep -q "# hagezi_nosafesearch" "$LIVE_BLOCKLIST" 2>/dev/null; then
        sed -i '/^# hagezi_nosafesearch/,/^$/d' "$LIVE_BLOCKLIST"
        logger -t parental-privacy "SafeSearch: hagezi_nosafesearch removed from live blocklist."
    fi
}


# ── HaGeZi TikTok integration ─────────────────────────────────────────────────
# When the "undesirable" block is enabled we also force-enable hagezi_tiktok in
# UCI and immediately append its entries to the live blocklist.  This extends
# the hardcoded TikTok/Snapchat domain list with HaGeZi's full coverage of
# ByteDance tracking, fingerprinting CDNs, and TikTok infrastructure domains.
#
# On disable we remove the appended block from the live file.  The UCI enabled
# flag is never forced back to 0 — user's own selection is always preserved.
HAGEZI_TIKTOK_URL="https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/tiktok.txt"
HAGEZI_TIKTOK_CACHE="/tmp/hagezi_tiktok.cache"

_tiktok_enable_uci() {
    local _existing
    _existing=$(uci -q get parental_privacy.blocklist_hagezi_tiktok.id 2>/dev/null)
    if [ -z "$_existing" ]; then
        uci -q batch <<EOI
set parental_privacy.blocklist_hagezi_tiktok=blocklist
set parental_privacy.blocklist_hagezi_tiktok.id='hagezi_tiktok'
set parental_privacy.blocklist_hagezi_tiktok.name='TikTok Block'
set parental_privacy.blocklist_hagezi_tiktok.url='${HAGEZI_TIKTOK_URL}'
set parental_privacy.blocklist_hagezi_tiktok.size_hint='small'
set parental_privacy.blocklist_hagezi_tiktok.description='Specific block for TikTok and its tracking/fingerprinting infrastructure.'
set parental_privacy.blocklist_hagezi_tiktok.enabled='1'
EOI
    else
        uci -q set parental_privacy.blocklist_hagezi_tiktok.enabled='1'
    fi
    uci -q commit parental_privacy
}

_tiktok_append_live() {
    [ -f "$LIVE_BLOCKLIST" ] || return

    if [ ! -s "$HAGEZI_TIKTOK_CACHE" ]; then
        logger -t parental-privacy "SafeSearch: fetching hagezi_tiktok list..."
        if wget -q --timeout=20 -O "${HAGEZI_TIKTOK_CACHE}.tmp" "$HAGEZI_TIKTOK_URL" 2>/dev/null; then
            if grep -qE '^(address|server)=/' "${HAGEZI_TIKTOK_CACHE}.tmp" 2>/dev/null; then
                mv "${HAGEZI_TIKTOK_CACHE}.tmp" "$HAGEZI_TIKTOK_CACHE"
                logger -t parental-privacy "SafeSearch: hagezi_tiktok fetched ($(wc -l < "$HAGEZI_TIKTOK_CACHE") lines)."
            else
                rm -f "${HAGEZI_TIKTOK_CACHE}.tmp"
                logger -t parental-privacy "SafeSearch: hagezi_tiktok download invalid — skipping live append."
                return
            fi
        else
            rm -f "${HAGEZI_TIKTOK_CACHE}.tmp"
            logger -t parental-privacy "SafeSearch: hagezi_tiktok download failed — will be included at next 03:00 update."
            return
        fi
    fi

    if grep -q "# hagezi_tiktok" "$LIVE_BLOCKLIST" 2>/dev/null; then
        logger -t parental-privacy "SafeSearch: hagezi_tiktok already present in live blocklist."
        return
    fi

    {
        echo ""
        echo "# hagezi_tiktok — appended by safesearch.sh"
        grep -E '^(address|server)=/' "$HAGEZI_TIKTOK_CACHE"
    } >> "$LIVE_BLOCKLIST"

    logger -t parental-privacy "SafeSearch: hagezi_tiktok appended to live blocklist."
}

_tiktok_remove_live() {
    [ -f "$LIVE_BLOCKLIST" ] || return
    if grep -q "# hagezi_tiktok" "$LIVE_BLOCKLIST" 2>/dev/null; then
        sed -i '/^# hagezi_tiktok/,/^$/d' "$LIVE_BLOCKLIST"
        logger -t parental-privacy "SafeSearch: hagezi_tiktok removed from live blocklist."
    fi
}


enable_safesearch() {
    mkdir -p /tmp/dnsmasq.kids.d
    mkdir -p /etc/dnsmasq.kids.d
    write_conf
    cp "$DNSMASQ_CONF" "$DNSMASQ_CONF_PERSIST"
    _nosafesearch_enable_uci
    _nosafesearch_append_live
    # Enable hagezi_tiktok if undesirable block is on
    BLOCK_UNDESIRABLE=$(uci -q get parental_privacy.default.undesirable)
    if [ "$BLOCK_UNDESIRABLE" = "1" ]; then
        _tiktok_enable_uci
        _tiktok_append_live
    fi
    /etc/init.d/dnsmasq restart
    logger -t parental-privacy "SafeSearch enabled (YouTube=${YOUTUBE_MODE}; block_search=${BLOCK_SEARCH}; nosafesearch=1; tiktok=${BLOCK_UNDESIRABLE})"
}

disable_safesearch() {
    rm -f "$DNSMASQ_CONF"
    rm -f "$DNSMASQ_CONF_PERSIST"
    _nosafesearch_remove_live
    _tiktok_remove_live
    /etc/init.d/dnsmasq restart
    logger -t parental-privacy "SafeSearch disabled"
}

status_safesearch() {
    # Check both locations — live RAM copy takes precedence
    if [ -f "$DNSMASQ_CONF" ] || [ -f "$DNSMASQ_CONF_PERSIST" ]; then
        echo "enabled"
    else
        echo "disabled"
    fi
}

case "$1" in
    enable)  enable_safesearch ;;
    disable) disable_safesearch ;;
    status)  status_safesearch ;;
    *)
        echo "Usage: $0 {enable|disable|status}"
        exit 1
        ;;
esac
