#!/bin/sh
# /usr/share/parental-privacy/safesearch.sh
#
# Enforces SafeSearch on Google, Bing, and YouTube via dnsmasq CNAME/address
# records. Works by pointing search domains at the provider's own SafeSearch
# enforcement IPs — no DPI or SSL inspection required.
#
# Usage:
#   safesearch.sh enable   — write rules and restart dnsmasq
#   safesearch.sh disable  — remove rules and restart dnsmasq
#   safesearch.sh status   — print current state

DNSMASQ_CONF="/etc/dnsmasq.d/safesearch.conf"

# ── Google ───────────────────────────────────────────────────────────────────
# forcesafesearch.google.com is Google's official SafeSearch enforcement host.
# We CNAME all regional and product Google search domains to it.
# Google then enforces SafeSearch server-side on every result page.
GOOGLE_SAFE_HOST="forcesafesearch.google.com"
GOOGLE_DOMAINS="
www.google.com
www.google.co.uk
www.google.com.au
www.google.ca
www.google.de
www.google.fr
www.google.es
www.google.it
www.google.co.jp
www.google.co.in
www.google.com.br
www.google.com.mx
www.google.nl
www.google.pl
www.google.ru
www.google.se
www.google.ch
www.google.be
www.google.at
www.google.dk
www.google.fi
www.google.no
www.google.pt
www.google.ie
www.google.co.nz
www.google.co.za
www.google.com.ar
www.google.com.co
www.google.com.pe
www.google.gr
www.google.hu
www.google.cz
www.google.ro
www.google.bg
www.google.hr
www.google.sk
www.google.si
www.google.lt
www.google.lv
www.google.ee
"

# ── Bing ─────────────────────────────────────────────────────────────────────
# strict.bing.com is Microsoft's SafeSearch enforcement host.
BING_SAFE_HOST="strict.bing.com"
BING_DOMAINS="
www.bing.com
bing.com
"

# ── YouTube ──────────────────────────────────────────────────────────────────
# restrict.youtube.com = Moderate restriction (blocks most adult content)
# restrictmd.youtube.com = Strict restriction (supervised mode, very locked down)
# Moderate is the better default — strict blocks too much legitimate content.
YOUTUBE_SAFE_HOST="restrict.youtube.com"
YOUTUBE_DOMAINS="
www.youtube.com
m.youtube.com
youtubei.googleapis.com
youtube.googleapis.com
www.youtube-nocookie.com
"

# ── DuckDuckGo ───────────────────────────────────────────────────────────────
# DuckDuckGo doesn't have a dedicated SafeSearch IP, but adding &kp=1 to
# queries via a redirect is not possible at DNS level. Best option is to
# block DuckDuckGo entirely so kids use a filtered engine instead.
# Set BLOCK_DUCKDUCKGO=1 to enable, 0 to leave DuckDuckGo accessible.
BLOCK_DUCKDUCKGO=1
DUCKDUCKGO_DOMAINS="
duckduckgo.com
www.duckduckgo.com
"

write_conf() {
    cat > "$DNSMASQ_CONF" <<EOF
# SafeSearch enforcement — managed by parental-privacy
# Generated by safesearch.sh — do not edit manually

EOF

    # Google — CNAME all regional domains to the safe host
    echo "# Google SafeSearch" >> "$DNSMASQ_CONF"
    for domain in $GOOGLE_DOMAINS; do
        echo "cname=${domain},${GOOGLE_SAFE_HOST}" >> "$DNSMASQ_CONF"
    done
    echo "" >> "$DNSMASQ_CONF"

    # Bing
    echo "# Bing SafeSearch" >> "$DNSMASQ_CONF"
    for domain in $BING_DOMAINS; do
        echo "cname=${domain},${BING_SAFE_HOST}" >> "$DNSMASQ_CONF"
    done
    echo "" >> "$DNSMASQ_CONF"

    # YouTube
    echo "# YouTube Restricted Mode" >> "$DNSMASQ_CONF"
    for domain in $YOUTUBE_DOMAINS; do
        echo "cname=${domain},${YOUTUBE_SAFE_HOST}" >> "$DNSMASQ_CONF"
    done
    echo "" >> "$DNSMASQ_CONF"

    # DuckDuckGo — block by pointing at 0.0.0.0
    if [ "$BLOCK_DUCKDUCKGO" = "1" ]; then
        echo "# DuckDuckGo blocked (no SafeSearch enforcement IP available)" >> "$DNSMASQ_CONF"
        for domain in $DUCKDUCKGO_DOMAINS; do
            echo "address=/${domain}/0.0.0.0" >> "$DNSMASQ_CONF"
            echo "address=/${domain}/::" >> "$DNSMASQ_CONF"
        done
        echo "" >> "$DNSMASQ_CONF"
    fi
}

enable_safesearch() {
    write_conf
    /etc/init.d/dnsmasq restart
    logger -t parental-privacy "SafeSearch enabled (Google, Bing, YouTube restricted mode)"
}

disable_safesearch() {
    rm -f "$DNSMASQ_CONF"
    /etc/init.d/dnsmasq restart
    logger -t parental-privacy "SafeSearch disabled"
}

status_safesearch() {
    if [ -f "$DNSMASQ_CONF" ]; then
        echo "enabled"
    else
        echo "disabled"
    fi
}

case "$1" in
    enable)  enable_safesearch ;;
    disable) disable_safesearch ;;
    status)  status_safesearch ;;
    *)
        echo "Usage: $0 {enable|disable|status}"
        exit 1
        ;;
esac
